dist: bionic

language: c

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libnotify-dev libsystemd-dev afl

env: AFL_NO_UI=1

jobs:
  include:
    - name: Fuzz config files
      script:
      - sudo sh -c 'echo core > /proc/sys/kernel/core_pattern'
      - 'timeout -s INT --preserve-status 10m make fuzz-configs; [[ $? == 130 ]]'
      - 'if (( "$(find fuzz/configs/results/*/crashes -type f | wc -l)" != 0 )); then grep . fuzz/configs/results/*/crashes/*; exit 1; fi'

    - name: Fuzz pressure files
      script:
      - sudo sh -c 'echo core > /proc/sys/kernel/core_pattern'
      - 'timeout -s INT --preserve-status 3m make fuzz-pressures; [[ $? == 130 ]]'
      - 'if (( "$(find fuzz/pressures/results/*/crashes -type f | wc -l)" != 0 )); then grep . fuzz/pressures/results/*/crashes/*; exit 1; fi'

    - name: Run unit tests
      script: make test

    - name: Build clang-tidy
      script: make clang-tidy

    - name: Build clang-everything
      script: make clang-everything

    - name: Run unit tests (WANT_SD_NOTIFY=0)
      script: make test WANT_SD_NOTIFY=0

    - name: Build clang-tidy (WANT_SD_NOTIFY=0)
      script: make clang-tidy WANT_SD_NOTIFY=0

    - name: Build clang-everything (WANT_SD_NOTIFY=0)
      script: make clang-everything WANT_SD_NOTIFY=0

    - name: Run unit tests (ppc64le)
      script: make test
      arch: ppc64le

    - name: Run unit tests (s390x)
      script: make test
      arch: s390x

    - name: Run unit tests (arm64)
      script: make test
      arch: arm64
